sudo : required
services: 
        - docker

before_install:
        - docker build -t web:v1 .
script:
        - docker run web:v1

deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: docker-deploy
        env: "DockerDeploy-env"
        bucket_name: "elasticbeanstalk-us-east-1-148585977622"
        bucket_path: "docker-deploy"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
